name: Coverage

on:
  push:
    branches: ["master","main"]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: yarn install --silent --frozen-lockfile
      - run: yarn test --coverage=true

      - uses: codecov/codecov-action@v1
        with:
          token: "ce9b0b47-ca45-48d4-807e-86b8fd345145"
          fail_ci_if_error: true
